name: Deploy Spring Boot Application

on:
  push:
    branches:
      - main  # Trigger deployment on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up OpenJDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Cache Maven Dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-m2

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: List target directory (Debug Step)
      run: ls -al target

    - name: Deploy using rsync
      env:
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
      run: |
        # Define variables
        APP_NAME=chatfill-bot-java.jar
        LOCAL_APP_PATH=target/*.jar
        REMOTE_DIR=/www/wwwroot/test.chatfil.com

        # Add server to known hosts (secure method)
        ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts

        # Use rsync to upload the file
        sshpass -p "$SERVER_PASSWORD" rsync -avz $LOCAL_APP_PATH $SERVER_USER@$SERVER_IP:$REMOTE_DIR/$APP_NAME

        # Restart the application on the server
        sshpass -p "$SERVER_PASSWORD" ssh $SERVER_USER@$SERVER_IP << EOF
          cd $REMOTE_DIR
          pkill -f $APP_NAME || true
          nohup java -jar $APP_NAME > app.log 2>&1 &
        EOF
